services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    working_dir: /app
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
