services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - ./server/.env
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development
      - PORT=8000
      - POSTGRES_HOST=postgres
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    working_dir: /app
    command: yarn dev
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  postgres_data:
