version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-management-server
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
